#!/bin/bash

# Navigate to the profile directory
cd /usr/sap/"$DB_SID"/D*/work

# Assign the command-line argument to the SAP_LOG_FILE variable
SAP_LOG_FILE=available.log

# Check if the log file exists
if [ ! -f "$SAP_LOG_FILE" ]; then
    echo "CRITICAL - SAP log file not found: $SAP_LOG_FILE"
    exit 1  # Exit with warning status
fi

# Extract the last line from the log file
LAST_LOG_ENTRY=$(tail -1 "$SAP_LOG_FILE")

# Check if the last log entry contains the "unavailable" keyword
if echo "$LAST_LOG_ENTRY" | grep -q "unavailable"; then
    # Extract and print the timestamp from the last log entry
    TIMESTAMP=$(echo "$LAST_LOG_ENTRY" | sed 's/Unavailable//g' ) 
    echo "CRITICAL - R3 Instance is down during prime time. Timestamp: $TIMESTAMP"
    exit 2  # Exit with critical status
else
    echo "OK - R3 Instance is available during prime time"
    exit 0  # Exit with OK status
fi

